### ISSUE TITLE
MWV Sentence error

### ISSUE THREAD

**Issue by jonjonr6** [sankeysoft/nmea_dashboard#13]
MWV is making the assumption that incoming wind speed value is in m/S rather than the actual units specified in the sentence (M=m/S, N=Knots, K=km/hr)
E.G. 
$WIMWV,270,R,10,N,A*17 =  apparent wind 270 deg from bow at 10 knts displays as:

AWS 19.4 kt
AWA 270

Although this can be "corrected" using derived data feature it would be better to fix the bug.

Also, I believe that the element described as True Wind Direction TWD might be better described as True WInd Angle (from the bow if the boat was stationary) to avoid confusion.

Nice, APP, much appreciated thank you.

**Comment by jodysankey** [comment]
This should be fixed in v 0.3.8 which I'm just testing at the moment. Thank you for the very helpful bug report.

With wind speed it had been trying to parse the units but the nmea reference I'd been using had missed the N=knots part so it was not doing it correctly.

With TWA vs TWD thank you for catching that, that's a very important one. I've added a new true wind angle datatype which is now populated from MWV and I'm now pulling what is actually the true wind direction from MDA instead.
