### ISSUE TITLE
Unsupported nmea messages

### ISSUE THREAD

**Issue by mikewestonip** [sankeysoft/nmea_dashboard#4]
21:35:02 WARNING Error parsing $GPRMC,13500,A,1819.947,N,06457.946,W,0.00,204.0,200803,0.0,W*7E Unsupported message type

**Comment by jodysankey** [comment]
Thanks for trying the app and taking the time to file feedback.

Different equipment manufacturers have defined many different NMEA messages, the app lumps every message in one of 3 categories:
1. Messages the app parses and uses
2. Messages the app explicitly ignores (usually because they are obsolete, are duplicates of the information in other more common messages, are not very useful, or contain information that I've not got around to supporting yet)
3. Messages are not yet placed in either category 1 or 2.

RMC is in category 3 hence why it shows as a warning. Looks like its a proprietary Garmin message for GPS configuration and in particular for describing a custom datum. I'm not seeing anything in there that looks very interesting and so I'm inclined to place it in category 2 - that would remove the warning but would not make the content of the message available.

Please can you confirm whether there is something specific that you'd like to use out of RMC?

**Comment by mikewestonip** [comment]
Thanks for the reply Jody.   I got a little more testing done.

I use a device called NMEA4WIFI.  It's a Seatalk converter one can use with Raymarine networks.   There is not a lot of documentation.  A guy in Portugal makes them and collaborates with his users to test fix and enhance.

It is creating four NMEA sentences that you are not yet supporting.  RMC, HDM, DBT and RSA.   Within RMC is the only source I get for variation, speed over ground and course over ground (track made good).    HDM is my only source of autopilot heading.   I've pasted below some of the data from my device as well as documentation from: 

https://gpsd.gitlab.io/gpsd/NMEA.html

which is a pretty good source for NMEA syntax. 

Below, the lines beginning $ are the data transmitted over wifi by my device, ... are comments the device puts in its debug log,  the remainder is the description from the above website.

Thanks for your efforts on this.  I was writing a similar app some years ago, but it fell into the unfinished projects hole!

 RMC - Recommended Minimum Navigation Information 

 $GPRMC,230830,A,1755.039,N,06443.653,W,5.50,357.0,250803,0.0,W*48 
     ... GPS MCOG (357.0)M received = (357.0)True ...

This is one of the sentences commonly emitted by GPS units.
        1         2 3       4 5        6  7   8   9    10 11
        |         | |       | |        |  |   |   |    |  |
 $--RMC,hhmmss.ss,A,ddmm.mm,a,dddmm.mm,a,x.x,x.x,xxxx,x.x,a*hh<CR><LF>
NMEA 2.3:
 $--RMC,hhmmss.ss,A,ddmm.mm,a,dddmm.mm,a,x.x,x.x,xxxx,x.x,a,m*hh<CR><LF>
NMEA 4.1:
 $--RMC,hhmmss.ss,A,ddmm.mm,a,dddmm.mm,a,x.x,x.x,xxxx,x.x,a,m,s*hh<CR><LF>
Field Number:
1.	UTC of position fix, hh is hours, mm is minutes, ss.ss is seconds.
2.	Status, A = Valid, V = Warning
3.	Latitude, dd is degrees. mm.mm is minutes.
4.	N or S
5.	Longitude, ddd is degrees. mm.mm is minutes.
6.	E or W
7.	Speed over ground, knots
8.	Track made good, degrees true
9.	Date, ddmmyy
10.	Magnetic Variation, degrees
11.	E or W
12.	FAA mode indicator (NMEA 2.3 and later)
13.	Nav Status (NMEA 4.1 and later) A=autonomous, D=differential, E=Estimated, M=Manual input mode N=not valid, S=Simulator, V = Valid
14.	Checksum
A status of V means the GPS has a valid fix that is below an internal quality threshold, e.g. because the dilution of precision is too high or an elevation mask test failed.
The number of digits past the decimal point for Time, Latitude and Longitude is model dependent.
Example: $GNRMC,001031.00,A,4404.13993,N,12118.86023,W,0.146,,100117,,,A*7B



 DBT - Depth below transducer

$SDDBT,58.10,f,17.71,M,,F*24 
     ... Depth below transducer 58.10 Feet ...

        1   2 3   4 5   6 7
        |   | |   | |   | |
 $--DBT,x.x,f,x.x,M,x.x,F*hh<CR><LF>
Field Number:
1.	Water depth, feet
2.	f = feet
3.	Water depth, meters
4.	M = meters
5.	Water depth, Fathoms
6.	F = Fathoms
7.	Checksum
In real-world sensors, sometimes not all three conversions are reported. So you might see something like $SDDBT,,f,22.5,M,,F*cs
Example: $SDDBT,7.8,f,2.4,M,1.3,F*0D



 RSA - Rudder Sensor Angle

 $IIRSA,-2,A,,V*48 
        1   2 3   4 5
        |   | |   | |
 $--RSA,x.x,A,x.x,A*hh<CR><LF>
Field Number:
1.	Starboard (or single) rudder sensor, "-" means Turn To Port
2.	Status, A = valid, V = Invalid
3.	Port rudder sensor
4.	Status, A = valid, V = Invalid
5.	Checksum


     
HDM - Heading - Magnetic

$GPHDM,6.0,M*33 
     ... Autopilot data inc heading[6.0] ...

Vessel heading in degrees with respect to magnetic north produced by any device or system producing magnetic heading.
        1   2 3
        |   | |
 $--HDM,x.x,M*hh<CR><LF>
Field Number:
1.	Heading Degrees, magnetic
2.	M = magnetic
3.	Checksum

**Comment by jodysankey** [comment]
Great, thank you. Those example messages and understanding your use case is very helpful. I'll add support for at least some of these sentences - can't find where I was seeing RMC as the datum sentence but from your example it clearly wasn't correct.

I need to add some infrastructure to handle pulling the same data element from different sources with some stickiness and in particular there is some bespoke handling I did for magvar that will need to change so its likely to take me a couple of weeks.

**Comment by jodysankey** [comment]
In 0.2.4 I added support for RMC, DBT, and HDM (plus a few other autopilot messages). Just pushed this version live on the play store so I'm interested how it works for you.

HDM was a bit harder than the others since all the calculations are still in true under the hood but things should work so long as the variation is populated by RMC.

RSA was already a supported message type and I've seen it work correctly across a few different boats so please could you confirm if you're still having issues with that?

**Comment by mikewestonip** [comment]
Thanks Jody.  I'm on the way from the Virgin Islands back to Tampa, and just now passing through the Florida Keys had mobile service for the first time in a while.   I loaded the new version and will test during my morning watch.
________________________________

**Comment by jodysankey** [comment]
Closing out this old issue on the assumption the previous fix worked.
